[package]
name = "lightning"
version = "0.2.0"
authors = ["Hao Shi <shisoftgenius@gmail.com>"]
edition = "2018"
license-file = "LICENSE"
description = "A set of lock-free data structures"


[dependencies]
log = "0.4.8"
seahash = "*"
smallvec = "1.2.0"
crossbeam-utils = "*"
crossbeam-epoch = "*"
num_cpus = "1.12.0"
libc = "0.2.69"
parking_lot = "0.10.2"

[dev-dependencies]
chashmap = "2.2.2"
bustle = "0.4.1"
tracing-subscriber = "0.2"
page_size = "0.4.2"
env_logger = "0.7.1"

[[test]]
name = "lightning-bench"
path = "test/bench/mod.rs"

[lib]
name = "lightning"
path = "src/lib.rs"

[features]
default = []
exchange_backoff = []