[package]
name = "lightling"
version = "0.1.0"
authors = ["Hao Shi <shisoftgenius@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.8"
seahash = "*"
smallvec = "1.2.0"
crossbeam-utils = "*"
crossbeam-epoch = "*"
num_cpus = "1.12.0"
page_size = "0.4.2"
bustle = "0.4.1"
tracing-subscriber = "0.2"
libc = "0.2.69"
chashmap = "2.2.2"

[[bin]]
name = "lighting-bench"
path = "src/bench/mod.rs"

[lib]
name = "lightling"
path = "src/lib.rs"