[package]
name = "lightning-bench"
version = "0.2.0"
authors = ["Hao Shi <haoshi@umass.edu>"]
edition = "2018"
license-file = "LICENSE"
description = "Bench for lightning"
repository = "https://github.com/ShisoftResearch/Lightning"
homepage = "https://github.com/ShisoftResearch/Lightning"
categories = ["data-structures", "lock-free", "wait-free"]

[dependencies]
lightning-containers = {path = "../"}
tracing-subscriber = {version = "0.2"}
bustle = {version = "0.4.1"}
num_cpus = "1"
chashmap = "2.2.2"

[[bin]]
name = "lightning-bench"
path = "mod.rs"